set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

set -g mouse on
setw -g mode-keys vi
set -sg escape-time 10

# ── Catppuccin ───────────────────────────────────────
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_flavor 'latte'
run '~/.tmux/plugins/tpm/tpm'
